eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix:  /api
  routes:
    organization-service: /organization/**
    licensing-service: /licensing/**
ribbon.connectionTimeout: 2000
ribbon.ReadTimeout: 2000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 8000
hystrix.command.licensing-service.execution.isolation.thread.timeoutInMilliseconds: 18000
licensing-service.ribbon.ReadTimeout: 7000

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ofedorova: DEBUG
