version: "3"

services:
  configserver:
    image: olgafedorova/config-server
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
  database:
    image: olgafedorova/microservices-db
    hostname: microservices-db
    container_name: microservices-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "microservices-db"
    networks:
      - microservices
  licensingservice:
    image: olgafedorova/licenses
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      ENCRYPT_KEY: "IMSYMMETRIC"

networks:
  microservices:
    driver: bridge
