spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    url: "jdbc:postgresql://database:5432/spring_microservices"
    username: "postgres"
    password: "{cipher}c43d6fe15ff61da8c3fe65c8748f8a5c4bb08311b6b3cc3bd170b0833a2932cf"
    driverClassName: "org.postgresql.Driver"
    testWhileIdle: "true"
    validationQuery: "SELECT 1 FROM pg_database WHERE datname='spring_microservices'"
    platform:  "postgres"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/