spring.datasource.url: "jdbc:postgresql://localhost:5433/spring_microservices"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user