server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
      config:
        server:
          native:
            search-locations: file:///C://Projects/samples/spring-microservices-in-action/config-server/src/main/resources/config/{application}